modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT License"

[[mods]] #mandatory
modId="inventory-sorter" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Inventory Sorter" #mandatory
#credits="Thanks for this example mod goes to Java" #optional
authors="Dhundup Tsering and Carson He" #optional
description='''
Automatically sorts inventories
'''
